# Generated by Django 5.2.17 on 2026-10-01 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0018_solicitante_externo_e_local_dos_arquivos'),
        ('core', '0010_remove_site_company_site_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('EMAIL', 'E-mail'), ('TEAMS', 'Teams'), ('USUARIO', 'Pedido verbal ou conversa'), ('FORMULARIO', 'Formulário')], default='EMAIL', max_length=12, verbose_name='origem')),
                ('external_id', models.CharField(blank=True, help_text='Identificador do e-mail ou da mensagem na origem. Vazio no registro manual.', max_length=255, verbose_name='identificador externo')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='assunto')),
                ('sender_name', models.CharField(blank=True, max_length=150, verbose_name='nome do remetente')),
                ('sender_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail do remetente')),
                ('raw_content', models.TextField(help_text='Texto puro, exatamente como chegou. Nunca é exibido como HTML.', verbose_name='texto recebido')),
                ('content_hash', models.CharField(db_index=True, editable=False, max_length=64, verbose_name='assinatura do conteúdo')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='recebida em')),
                ('status', models.CharField(choices=[('NOVO', 'Nova'), ('CONVERTIDO', 'Virou demanda'), ('IGNORADO', 'Ignorada')], default='NOVO', max_length=10, verbose_name='situação')),
                ('suggested_title', models.CharField(blank=True, max_length=200, verbose_name='título sugerido')),
                ('suggested_deadline', models.DateTimeField(blank=True, null=True, verbose_name='prazo sugerido')),
                ('confidence', models.PositiveSmallIntegerField(default=0, verbose_name='confiança (0 a 100)')),
                ('suggestion_reasons', models.JSONField(blank=True, default=list, verbose_name='por que a LPS sugeriu isso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrada no sistema em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='tratada em')),
                ('resolution_note', models.CharField(blank=True, max_length=255, verbose_name='motivo')),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_item', to='activities.activity', verbose_name='atividade criada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_items_created', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intake_items', to='core.organization', verbose_name='organização')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='tratada por')),
                ('suggested_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.client', verbose_name='cliente sugerido')),
                ('suggested_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sector', verbose_name='setor sugerido')),
                ('suggested_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.site', verbose_name='obra sugerida')),
            ],
            options={
                'verbose_name': 'solicitação',
                'verbose_name_plural': 'solicitações',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IntakeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('EDITADA', 'Sugestões corrigidas'), ('CONVERTIDA', 'Virou demanda'), ('IGNORADA', 'Ignorada'), ('RESTAURADA', 'Restaurada')], max_length=12, verbose_name='tipo')),
                ('note', models.TextField(blank=True, verbose_name='detalhe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='quando')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='intake.intakeitem', verbose_name='solicitação')),
            ],
            options={
                'verbose_name': 'evento da solicitação',
                'verbose_name_plural': 'eventos da solicitação',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='intakeitem',
            index=models.Index(fields=['organization', 'status', '-received_at'], name='intake_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='intakeitem',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('organization', 'source', 'external_id'), name='unique_intake_external_id_per_source'),
        ),
        migrations.AddConstraint(
            model_name='intakeitem',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 100)), name='intake_confidence_0_100'),
        ),
    ]
