# Generated by Django 5.2.17 on 2026-10-01 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_atividade_vira_demanda_nos_rotulos'),
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakeitem',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_item', to='activities.activity', verbose_name='demanda criada'),
        ),
    ]
