databases:
  - name: lps-db
    plan: free
    databaseName: lps
    user: lps

services:
  - type: web
    name: lps-web
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: lps-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.7

  - type: cron
    name: lps-check-overdue-tasks
    runtime: python
    plan: free
    schedule: "0 * * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py check_overdue_tasks"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: lps-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.7
