# Generated by Django 5.2.17 on 2026-09-25 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_stages', to='core.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'estágio de tarefa',
                'verbose_name_plural': 'estágios de tarefa',
                'ordering': ['organization', 'order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_taskstage_name_per_org')],
            },
        ),
    ]
