# Generated by Django 5.2.17 on 2026-09-25 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_taskstage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('color', models.PositiveSmallIntegerField(choices=[(0, 'Cinza'), (1, 'Azul'), (2, 'Verde'), (3, 'Amarelo'), (4, 'Laranja'), (5, 'Vermelho'), (6, 'Roxo')], default=0, verbose_name='cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'marcador',
                'verbose_name_plural': 'marcadores',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_tag_name_per_org')],
            },
        ),
    ]
