# Generated by Django 5.2.17 on 2026-09-26 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color_hex',
            field=models.CharField(default='#94A3B8', max_length=7, verbose_name='cor'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='color',
            field=models.CharField(default='#94A3B8', help_text='Só decoração da coluna do Kanban — nunca afeta o status operacional da tarefa.', max_length=7, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Cinza'), (1, 'Azul'), (2, 'Verde'), (3, 'Amarelo'), (4, 'Laranja'), (5, 'Vermelho'), (6, 'Roxo')], default=0, verbose_name='cor (legado)'),
        ),
        migrations.CreateModel(
            name='EnumColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('activity_status', 'Status da atividade'), ('task_status', 'Status da tarefa'), ('activity_urgency', 'Prioridade da atividade')], max_length=32, verbose_name='domínio')),
                ('code', models.CharField(max_length=32, verbose_name='código')),
                ('color', models.CharField(max_length=7, verbose_name='cor')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enum_colors', to='core.organization', verbose_name='organização')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'cor de status/prioridade',
                'verbose_name_plural': 'cores de status/prioridade',
                'constraints': [models.UniqueConstraint(fields=('organization', 'domain', 'code'), name='unique_enumcolor_per_org_domain_code')],
            },
        ),
    ]
