# Generated by Django 5.2.17 on 2026-09-27 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tag_color_hex_finalize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ordem')),
                ('color', models.CharField(default='#94A3B8', help_text='So decoracao do fluxo visual; nunca afeta o status operacional da atividade.', max_length=7, verbose_name='cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_stages', to='core.organization', verbose_name='organizacao')),
            ],
            options={
                'verbose_name': 'estagio de atividade',
                'verbose_name_plural': 'estagios de atividade',
                'ordering': ['organization', 'order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_activitystage_name_per_org')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('activity', 'Atividade'), ('task', 'Tarefa')], max_length=12, verbose_name='tipo')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descricao')),
                ('behavior', models.CharField(help_text='Codigo operacional que este status visual segue.', max_length=32, verbose_name='comportamento base')),
                ('color', models.CharField(default='#94A3B8', max_length=7, verbose_name='cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_statuses', to='core.organization', verbose_name='organizacao')),
            ],
            options={
                'verbose_name': 'status configuravel',
                'verbose_name_plural': 'status configuraveis',
                'ordering': ['organization', 'domain', 'name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'domain', 'name'), name='unique_workflowstatus_name_per_org_domain')],
            },
        ),
    ]
