# Generated by Django 5.2.17 on 2026-09-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activitystage_workflowstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumcolor',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='enumcolor',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='oculto'),
        ),
        migrations.AddField(
            model_name='enumcolor',
            name='label',
            field=models.CharField(blank=True, max_length=100, verbose_name='nome exibido'),
        ),
    ]
