# Generated by Django 5.2.17 on 2026-09-29 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_enumcolor_description_enumcolor_is_hidden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='company',
        ),
        migrations.AddField(
            model_name='site',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='core.client', verbose_name='cliente'),
        ),
    ]
