# Generated by Django 5.2.17 on 2026-10-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_site_company_site_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitystage',
            options={'ordering': ['organization', 'order', 'name'], 'verbose_name': 'estagio de demanda', 'verbose_name_plural': 'estagios de demanda'},
        ),
        migrations.AlterField(
            model_name='activitystage',
            name='color',
            field=models.CharField(default='#94A3B8', help_text='So decoracao do fluxo visual; nunca afeta o status operacional da demanda.', max_length=7, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='enumcolor',
            name='domain',
            field=models.CharField(choices=[('activity_status', 'Status da demanda'), ('task_status', 'Status da tarefa'), ('activity_urgency', 'Prioridade da demanda')], max_length=32, verbose_name='domínio'),
        ),
        migrations.AlterField(
            model_name='workflowstatus',
            name='domain',
            field=models.CharField(choices=[('activity', 'Demanda'), ('task', 'Tarefa')], max_length=12, verbose_name='tipo'),
        ),
    ]
