# Generated by Django 5.2.17 on 2026-10-01

import django.db.models.deletion
from django.db import migrations, models


def scope_visual_workflows(apps, schema_editor):
    """Copies the former organization-wide visual setup into every sector.

    Stage references are remapped to the matching sector. A demand without a
    sector, intentionally, loses the old global stage: a global stage must not
    silently leak into a sector-scoped workflow.
    """
    Activity = apps.get_model("activities", "Activity")
    Task = apps.get_model("activities", "Task")
    Sector = apps.get_model("core", "Sector")
    ActivityStage = apps.get_model("core", "ActivityStage")
    TaskStage = apps.get_model("core", "TaskStage")
    WorkflowStatus = apps.get_model("core", "WorkflowStatus")

    sectors_by_org = {}
    for sector in Sector.objects.all().order_by("organization_id", "pk"):
        sectors_by_org.setdefault(sector.organization_id, []).append(sector)

    def clone_per_sector(model, item_queryset, field_name):
        mapping = {}
        for source in list(model.objects.all().order_by("pk")):
            sectors = sectors_by_org.get(source.organization_id, [])
            if not sectors:
                source.delete()
                continue
            source_pk = source.pk
            by_sector = {}
            for index, sector in enumerate(sectors):
                if index == 0:
                    source.sector_id = sector.pk
                    source.save(update_fields=["sector"])
                    row = source
                else:
                    row = model.objects.create(
                        organization_id=source.organization_id,
                        sector_id=sector.pk,
                        name=source.name,
                        order=source.order,
                        color=source.color,
                        is_active=source.is_active,
                        is_default=False,
                        created_by_id=source.created_by_id,
                    )
                by_sector[sector.pk] = row.pk
            mapping[source_pk] = by_sector
        for item in item_queryset.exclude(**{f"{field_name}__isnull": True}).iterator():
            new_id = mapping.get(getattr(item, f"{field_name}_id"), {}).get(item.sector_id)
            if getattr(item, f"{field_name}_id") != new_id:
                item_queryset.filter(pk=item.pk).update(**{f"{field_name}_id": new_id})

    clone_per_sector(ActivityStage, Activity.objects.all(), "stage")
    clone_per_sector(TaskStage, Task.objects.all(), "stage")

    # Existing configurable statuses were never operational. Keep their labels
    # as conditions in each sector, but do not assign them to existing items.
    for source in list(WorkflowStatus.objects.all().order_by("pk")):
        sectors = sectors_by_org.get(source.organization_id, [])
        if not sectors:
            source.delete()
            continue
        for index, sector in enumerate(sectors):
            if index == 0:
                source.sector_id = sector.pk
                source.save(update_fields=["sector"])
            else:
                WorkflowStatus.objects.create(
                    organization_id=source.organization_id,
                    sector_id=sector.pk,
                    domain=source.domain,
                    name=source.name,
                    description=source.description,
                    behavior=source.behavior,
                    color=source.color,
                    order=source.order,
                    is_active=source.is_active,
                    is_default=False,
                    created_by_id=source.created_by_id,
                )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_atividade_vira_demanda_nos_rotulos"),
        ("activities", "0020_codigo_da_demanda"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitystage",
            name="sector",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activity_stages", to="core.sector", verbose_name="setor"),
        ),
        migrations.AddField(
            model_name="activitystage",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="etapa padrão"),
        ),
        migrations.AddField(
            model_name="taskstage",
            name="sector",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="task_stages", to="core.sector", verbose_name="setor"),
        ),
        migrations.AddField(
            model_name="taskstage",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="etapa padrão"),
        ),
        migrations.AddField(
            model_name="workflowstatus",
            name="sector",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="conditions", to="core.sector", verbose_name="setor"),
        ),
        migrations.AddField(
            model_name="workflowstatus",
            name="order",
            field=models.PositiveIntegerField(default=1, verbose_name="ordem"),
        ),
        migrations.AddField(
            model_name="workflowstatus",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="condição padrão"),
        ),
        migrations.AlterField(
            model_name="workflowstatus",
            name="behavior",
            field=models.CharField(blank=True, help_text="Legado: não é usado pela condição nem pelo motor operacional.", max_length=32, verbose_name="comportamento base"),
        ),
        migrations.RemoveConstraint(model_name="activitystage", name="unique_activitystage_name_per_org"),
        migrations.RemoveConstraint(model_name="taskstage", name="unique_taskstage_name_per_org"),
        migrations.RemoveConstraint(model_name="workflowstatus", name="unique_workflowstatus_name_per_org_domain"),
        migrations.RunPython(scope_visual_workflows, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="activitystage",
            name="sector",
            field=models.ForeignKey(help_text="Cada etapa pertence ao fluxo visual de um único setor.", on_delete=django.db.models.deletion.CASCADE, related_name="activity_stages", to="core.sector", verbose_name="setor"),
        ),
        migrations.AlterField(
            model_name="taskstage",
            name="sector",
            field=models.ForeignKey(help_text="Cada etapa pertence ao fluxo visual de um único setor.", on_delete=django.db.models.deletion.CASCADE, related_name="task_stages", to="core.sector", verbose_name="setor"),
        ),
        migrations.AlterField(
            model_name="workflowstatus",
            name="sector",
            field=models.ForeignKey(help_text="A condição só pode ser usada no setor a que pertence.", on_delete=django.db.models.deletion.CASCADE, related_name="conditions", to="core.sector", verbose_name="setor"),
        ),
        migrations.AlterModelOptions(name="activitystage", options={"ordering": ["organization", "sector", "order", "name"], "verbose_name": "etapa de demanda", "verbose_name_plural": "etapas de demanda"}),
        migrations.AlterModelOptions(name="taskstage", options={"ordering": ["organization", "sector", "order", "name"], "verbose_name": "etapa de tarefa", "verbose_name_plural": "etapas de tarefa"}),
        migrations.AlterModelOptions(name="workflowstatus", options={"ordering": ["organization", "sector", "domain", "order", "name"], "verbose_name": "condição", "verbose_name_plural": "condições"}),
        migrations.AddConstraint(model_name="activitystage", constraint=models.UniqueConstraint(fields=("organization", "sector", "name"), name="unique_activitystage_name_per_org_sector")),
        migrations.AddConstraint(model_name="activitystage", constraint=models.UniqueConstraint(condition=models.Q(("is_default", True)), fields=("organization", "sector"), name="one_default_activitystage_per_org_sector")),
        migrations.AddConstraint(model_name="taskstage", constraint=models.UniqueConstraint(fields=("organization", "sector", "name"), name="unique_taskstage_name_per_org_sector")),
        migrations.AddConstraint(model_name="taskstage", constraint=models.UniqueConstraint(condition=models.Q(("is_default", True)), fields=("organization", "sector"), name="one_default_taskstage_per_org_sector")),
        migrations.AddConstraint(model_name="workflowstatus", constraint=models.UniqueConstraint(fields=("organization", "sector", "domain", "name"), name="unique_condition_name_per_org_sector_domain")),
        migrations.AddConstraint(model_name="workflowstatus", constraint=models.UniqueConstraint(condition=models.Q(("is_default", True)), fields=("organization", "sector", "domain"), name="one_default_condition_per_org_sector_domain")),
    ]
