# Generated by Django 5.2.17 on 2026-10-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sector_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enumcolor',
            name='domain',
            field=models.CharField(choices=[('activity_status', 'Status da demanda'), ('task_status', 'Status da tarefa'), ('activity_urgency', 'Prioridade da demanda'), ('task_priority', 'Prioridade da tarefa')], max_length=32, verbose_name='domínio'),
        ),
    ]
