# Generated by Django 5.2.17 on 2026-09-15 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='resultado esperado')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('requested_deadline', models.DateTimeField(blank=True, null=True, verbose_name='prazo solicitado')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('BLOQUEADA', 'Bloqueada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=14, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('first_action_at', models.DateTimeField(blank=True, help_text='Marco de avanço operacional real, não apenas visualização (Regras 02 §45).', null=True, verbose_name='primeira ação em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelada em')),
                ('cancelled_reason', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('reopened_at', models.DateTimeField(blank=True, null=True, verbose_name='reaberta em')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='core.company', verbose_name='empresa')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.costcenter', verbose_name='centro de custo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='core.organization', verbose_name='organização')),
                ('owner', models.ForeignKey(help_text='Responsável único pelo acompanhamento até a resolução (Regras 01 §6.1).', on_delete=django.db.models.deletion.PROTECT, related_name='activities_owned', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.site', verbose_name='obra')),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
                'ordering': ['-created_at'],
                'permissions': [('can_view_all_activities', 'Pode visualizar todas as atividades da organização'), ('can_change_owner', 'Pode alterar o dono da atividade'), ('can_reopen_activity', 'Pode reabrir atividade concluída'), ('can_cancel_activity', 'Pode cancelar atividade')],
            },
        ),
        migrations.CreateModel(
            name='ActivityMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='enviada em')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='activities.activity', verbose_name='atividade')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'mensagem da atividade',
                'verbose_name_plural': 'mensagens da atividade',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='alterado em')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_changes', to='activities.activity', verbose_name='atividade')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='novo dono')),
                ('previous_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='dono anterior')),
            ],
            options={
                'verbose_name': 'alteração de dono',
                'verbose_name_plural': 'alterações de dono',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='posição atual')),
                ('queue_size_at_entry', models.PositiveIntegerField(verbose_name='total da fila na entrada')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='entrou na fila em')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='saiu da fila em')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='core.sector', verbose_name='setor')),
            ],
            options={
                'verbose_name': 'entrada na fila',
                'verbose_name_plural': 'entradas na fila',
                'ordering': ['sector', 'position'],
            },
        ),
        migrations.CreateModel(
            name='QueuePositionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_position', models.PositiveIntegerField(verbose_name='posição anterior')),
                ('new_position', models.PositiveIntegerField(verbose_name='nova posição')),
                ('old_total', models.PositiveIntegerField(verbose_name='total anterior')),
                ('new_total', models.PositiveIntegerField(verbose_name='novo total')),
                ('reason', models.CharField(choices=[('AUTOMATICA_CONCLUSAO', 'Automática (conclusão de tarefa anterior)'), ('AUTOMATICA_ENTRADA', 'Automática (nova entrada)'), ('MANUAL', 'Reordenação manual'), ('ENTRADA_PRIORITARIA', 'Entrada prioritária')], max_length=24, verbose_name='motivo')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='observação')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='alterado em')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Nulo quando a mudança é automática.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_changes', to='activities.queueentry', verbose_name='entrada na fila')),
            ],
            options={
                'verbose_name': 'mudança de posição na fila',
                'verbose_name_plural': 'mudanças de posição na fila',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='motivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_reasons', to='core.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'motivo de devolução',
                'verbose_name_plural': 'motivos de devolução',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ordem')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('status', models.CharField(choices=[('NAO_INICIADA', 'Não iniciada'), ('DISPONIVEL', 'Disponível'), ('EM_FILA', 'Em fila'), ('EM_EXECUCAO', 'Em execução'), ('BLOQUEADA', 'Bloqueada'), ('DEVOLVIDA', 'Devolvida'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='NAO_INICIADA', max_length=14, verbose_name='status')),
                ('requested_deadline', models.DateTimeField(blank=True, null=True, verbose_name='prazo solicitado')),
                ('committed_deadline', models.DateTimeField(blank=True, null=True, verbose_name='prazo comprometido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('first_action_at', models.DateTimeField(blank=True, null=True, verbose_name='primeira ação em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelada em')),
                ('overdue_notified_at', models.DateTimeField(blank=True, help_text='Evita reenviar a notificação/e-mail de atraso a cada verificação.', null=True, verbose_name='notificação de atraso enviada em')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='activities.activity', verbose_name='atividade')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('depends_on', models.ForeignKey(blank=True, help_text='Dependência simples: esta tarefa não deveria iniciar antes da conclusão da anterior (Regras 02 §29).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='activities.task', verbose_name='depende de')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.sector', verbose_name='setor responsável')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ['activity', 'order'],
                'permissions': [('can_assume_task', 'Pode assumir tarefa disponível'), ('can_assign_task', 'Pode atribuir executor a uma tarefa'), ('can_reorder_queue', 'Pode reordenar a fila do setor'), ('can_view_full_queue', 'Pode visualizar a fila completa do setor')],
            },
        ),
        migrations.CreateModel(
            name='SectorTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(auto_now_add=True, verbose_name='movido em')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='observação')),
                ('from_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.sector', verbose_name='setor de origem')),
                ('moved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='movido por')),
                ('to_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.sector', verbose_name='setor de destino')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_transfers', to='activities.task', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'movimentação de setor',
                'verbose_name_plural': 'movimentações de setor',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.AddField(
            model_name='queueentry',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='activities.task', verbose_name='tarefa'),
        ),
        migrations.CreateModel(
            name='DeadlineProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_deadline', models.DateTimeField(verbose_name='prazo proposto')),
                ('proposed_at', models.DateTimeField(auto_now_add=True, verbose_name='proposto em')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando decisão'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=10, verbose_name='status')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidido em')),
                ('decision_note', models.TextField(blank=True, verbose_name='motivo da recusa')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='decidido por')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='proposto por')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_proposals', to='activities.task', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'proposta de prazo',
                'verbose_name_plural': 'propostas de prazo',
                'ordering': ['-proposed_at'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('RESOLVIDO', 'Resolvido')], default='ABERTO', max_length=10, verbose_name='status')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='aberto em')),
                ('resolution_note', models.TextField(blank=True, verbose_name='resolução')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolvido em')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='resolvido por')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conflict', to='activities.deadlineproposal', verbose_name='proposta recusada')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_conflicts', to='activities.task', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'conflito de prazo',
                'verbose_name_plural': 'conflitos de prazo',
                'ordering': ['-opened_at'],
                'permissions': [('can_resolve_deadline_conflict', 'Pode resolver conflito de prazo')],
            },
        ),
        migrations.CreateModel(
            name='TaskBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='motivo')),
                ('observation', models.TextField(blank=True, verbose_name='observação')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='bloqueada em')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='desbloqueada em')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='desbloqueada por')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='bloqueada por')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='activities.task', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'bloqueio de tarefa',
                'verbose_name_plural': 'bloqueios de tarefa',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='incluído em')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='incluído por')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executors', to='activities.task', verbose_name='tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_executed', to=settings.AUTH_USER_MODEL, verbose_name='executor')),
            ],
            options={
                'verbose_name': 'executor da tarefa',
                'verbose_name_plural': 'executores da tarefa',
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='enviada em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='activities.task', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'mensagem da tarefa',
                'verbose_name_plural': 'mensagens da tarefa',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, verbose_name='observação')),
                ('returned_at', models.DateTimeField(auto_now_add=True, verbose_name='devolvida em')),
                ('from_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.sector', verbose_name='setor de origem')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='activities.returnreason', verbose_name='motivo')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='devolvida por')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='activities.task', verbose_name='tarefa')),
                ('to_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.sector', verbose_name='setor de destino')),
            ],
            options={
                'verbose_name': 'devolução',
                'verbose_name_plural': 'devoluções',
                'ordering': ['-returned_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='início')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('is_manual', models.BooleanField(default=False, help_text='Diferencia tempo capturado pelo timer de apropriação posterior (Regras 04 §113).', verbose_name='lançamento manual')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='activities.task', verbose_name='tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to=settings.AUTH_USER_MODEL, verbose_name='executor')),
            ],
            options={
                'verbose_name': 'sessão de trabalho',
                'verbose_name_plural': 'sessões de trabalho',
                'ordering': ['started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='returnreason',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_return_reason_per_org'),
        ),
    ]
