# Generated by Django 5.2.17 on 2026-09-16 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='process_version',
            field=models.ForeignKey(blank=True, help_text='Vínculo travado no momento da criação — publicar nova versão não altera atividades antigas (Regras 11 §19).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='processes.processversion', verbose_name='versão do processo aplicada'),
        ),
    ]
