# Generated by Django 5.2.17 on 2026-09-17 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_process_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='atribuído em')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando aceite'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=10, verbose_name='status')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidido em')),
                ('observation', models.TextField(blank=True, verbose_name='observação')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atribuído por')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='activities.returnreason', verbose_name='motivo da recusa')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='activities.task', verbose_name='tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='designado')),
            ],
            options={
                'verbose_name': 'atribuição de tarefa',
                'verbose_name_plural': 'atribuições de tarefa',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
