# Generated by Django 5.2.17 on 2026-09-19 12:00

import activities.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client'),
        ('activities', '0003_taskassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Quem solicitou o serviço.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.client', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Setor para quem a atividade é endereçada — distinto do setor de cada tarefa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designated_activities', to='core.sector', verbose_name='grupo designado'),
        ),
        migrations.AddField(
            model_name='activity',
            name='urgency',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=6, verbose_name='urgência'),
        ),
        migrations.AddField(
            model_name='activity',
            name='address',
            field=models.CharField(blank=True, help_text='Endereço adicional, além do cadastro do cliente.', max_length=255, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='activity',
            name='code',
            field=models.CharField(blank=True, editable=False, help_text='Gerado automaticamente ao salvar. Identifica a atividade e a pasta de anexos.', max_length=20, null=True, unique=True, verbose_name='código'),
        ),
        migrations.CreateModel(
            name='ActivityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=activities.models.activity_attachment_upload_to, verbose_name='arquivo')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='nome original')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='activities.activity', verbose_name='atividade')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'anexo da atividade',
                'verbose_name_plural': 'anexos da atividade',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
