# Generated by Django 5.2.17 on 2026-09-19 18:44

import os
import shutil

import activities.models
from django.conf import settings
from django.db import migrations, models


def move_existing_files(apps, schema_editor):
    """Leva os anexos já enviados de MEDIA_ROOT/activities/... para
    ACTIVITY_FILES_ROOT/<empresa>/<código>/... e atualiza o nome guardado."""
    Attachment = apps.get_model("activities", "ActivityAttachment")
    for att in Attachment.objects.select_related("activity__company"):
        old_path = os.path.join(settings.MEDIA_ROOT, att.file.name)
        if not os.path.isfile(old_path):
            continue
        activity = att.activity
        company = activities.models._folder_name(activity.company.name if activity.company_id else "", "sem-empresa")
        code = activity.code or f"sem-codigo/{activity.pk}"
        new_name = f"{company}/{code}/{os.path.basename(att.file.name)}"
        new_path = os.path.join(settings.ACTIVITY_FILES_ROOT, *new_name.split("/"))
        os.makedirs(os.path.dirname(new_path), exist_ok=True)
        shutil.move(old_path, new_path)
        att.file.name = new_name
        att.save(update_fields=["file"])


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_client_sector_urgency_and_more'),
    ]

    operations = [
        migrations.RunPython(move_existing_files, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='activityattachment',
            name='file',
            field=models.FileField(max_length=255, storage=activities.models.activity_files_storage, upload_to=activities.models.activity_attachment_upload_to, verbose_name='arquivo'),
        ),
    ]
