# Generated by hand for Django 5.2.17 (sandbox sem runtime Django — ver
# aviso no relatório: rodar `python manage.py makemigrations --check` depois
# de aplicar, para confirmar que nada ficou fora de sincronia).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_client_sector_urgency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(
                choices=[
                    ('ABERTA', 'Aberta'),
                    ('EM_ANDAMENTO', 'Em andamento'),
                    ('BLOQUEADA', 'Bloqueada'),
                    ('PENDENTE', 'Pendente'),
                    ('CONCLUIDA', 'Concluída'),
                    ('CANCELADA', 'Cancelada'),
                ],
                default='ABERTA',
                max_length=14,
                verbose_name='status',
            ),
        ),
        migrations.AddField(
            model_name='activity',
            name='completion_outcome',
            field=models.CharField(
                blank=True,
                choices=[
                    ('SUCESSO', 'Sucesso'),
                    ('CONCLUIDO_COM_PENDENCIAS', 'Concluído com pendências'),
                    ('DECLINADO', 'Declinado'),
                    ('CANCELADO', 'Cancelado'),
                ],
                help_text='Escolhido no popup de finalização — explica o que aconteceu além do status.',
                max_length=28,
                verbose_name='resultado da finalização',
            ),
        ),
        migrations.CreateModel(
            name='ActivityPendency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'reason',
                    models.CharField(
                        choices=[
                            ('APROVACAO_GESTOR', 'Aguardando aprovação do gestor'),
                            ('AJUSTES_REVISOES', 'Aguardando ajustes/revisões'),
                            ('MATERIAL', 'Aguardando material'),
                            ('INFORMACOES_CLIENTE', 'Aguardando informações do cliente'),
                        ],
                        max_length=20,
                        verbose_name='motivo',
                    ),
                ),
                ('comment', models.TextField(verbose_name='comentário')),
                (
                    'decision_deadline',
                    models.DateTimeField(
                        blank=True,
                        help_text='Obrigatório quando o motivo pede aprovação do gestor.',
                        null=True,
                        verbose_name='prazo para decisão do gestor',
                    ),
                ),
                (
                    'notify_client',
                    models.BooleanField(
                        default=False,
                        help_text="Só usado no motivo 'Aguardando informações do cliente'.",
                        verbose_name='enviar e-mail ao cliente',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('ABERTA', 'Aberta'), ('APROVADA', 'Aprovada'), ('ENCERRADA', 'Encerrada')],
                        default='ABERTA',
                        max_length=10,
                        verbose_name='status',
                    ),
                ),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='marcada em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolvida em')),
                ('resolution_comment', models.TextField(blank=True, verbose_name='comentário da aprovação')),
                (
                    'activity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pendencies',
                        to='activities.activity',
                        verbose_name='atividade',
                    ),
                ),
                (
                    'approver',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='gestor responsável',
                    ),
                ),
                (
                    'opened_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='marcada por',
                    ),
                ),
                (
                    'previous_owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='dono anterior',
                    ),
                ),
                (
                    'resolved_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='resolvida por',
                    ),
                ),
            ],
            options={
                'verbose_name': 'pendência da atividade',
                'verbose_name_plural': 'pendências da atividade',
                'ordering': ['-opened_at'],
            },
        ),
    ]
