# Generated by Django 5.2.17 on 2026-09-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_pendencies'),
        ('activities', '0005_attachment_storage_atividade'),
    ]

    operations = [
    ]
