# Generated by Django 5.2.17 on 2026-09-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_merge_20260919_1706'),
        ('core', '0003_taskstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Coluna do Kanban configurável por organização — camada visual, não altera o status operacional da tarefa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.taskstage', verbose_name='estágio'),
        ),
    ]
