# Generated by Django 5.2.17 on 2026-09-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_task_stage'),
        ('core', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='activities', to='core.tag', verbose_name='marcadores'),
        ),
        migrations.AddField(
            model_name='task',
            name='stage_changed_at',
            field=models.DateTimeField(blank=True, help_text='Quando `stage` mudou pela última vez — usado só para o indicador de tempo parado no Kanban.', null=True, verbose_name='estágio alterado em'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='core.tag', verbose_name='marcadores'),
        ),
    ]
