# Generated by Django 5.2.17 on 2026-09-25 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_activity_tags_task_stage_changed_at_task_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymessage',
            name='kind',
            field=models.CharField(choices=[('NORMAL', 'Mensagem'), ('DECISAO', 'Decisão registrada'), ('RISCO', 'Risco'), ('COMPROMISSO', 'Compromisso'), ('IMPEDIMENTO', 'Impedimento')], default='NORMAL', max_length=12, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='taskmessage',
            name='kind',
            field=models.CharField(choices=[('NORMAL', 'Mensagem'), ('DECISAO', 'Decisão registrada'), ('RISCO', 'Risco'), ('COMPROMISSO', 'Compromisso'), ('IMPEDIMENTO', 'Impedimento')], default='NORMAL', max_length=12, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='TaskChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='item')),
                ('is_done', models.BooleanField(default=False, verbose_name='concluído')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='marcado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='marcado por')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='activities.task', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'item de checklist',
                'verbose_name_plural': 'itens de checklist',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
