# Generated by Django 5.2.17 on 2026-09-27 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activitymessage_kind_taskmessage_kind_and_more'),
        ('core', '0008_activitystage_workflowstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Camada visual configuravel; nao altera o status operacional da atividade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.activitystage', verbose_name='estagio'),
        ),
        migrations.AddField(
            model_name='activity',
            name='stage_changed_at',
            field=models.DateTimeField(blank=True, help_text='Quando o estagio visual mudou pela ultima vez.', null=True, verbose_name='estagio alterado em'),
        ),
    ]
