# Generated by Django 5.2.17 on 2026-09-28 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_activity_stage_activity_stage_changed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Nunca aparece para o cliente; só para uso interno da equipe.', verbose_name='observações internas'),
        ),
        migrations.AddField(
            model_name='activity',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Quem pediu informalmente, dentro da própria organização — nunca o cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_requested', to=settings.AUTH_USER_MODEL, verbose_name='solicitante'),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Último toque — usado para saber há quanto tempo um rascunho está parado.', verbose_name='atualizada em'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Responsável único pelo acompanhamento até a resolução (Regras 01 §6.1). Só pode ficar em branco enquanto a atividade é um rascunho.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities_owned', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('BLOQUEADA', 'Bloqueada'), ('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=14, verbose_name='status'),
        ),
    ]
