# Generated by Django 5.2.17 on 2026-09-29 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_fix_stuck_em_execucao_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='responsavel',
            field=models.ForeignKey(blank=True, help_text='Quem responde pela conclusão da tarefa. Obrigatório desde a criação (imposto em TaskService.create_task) — nullable aqui só como passo de transição de schema até a migração de dados popular as tarefas existentes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.CreateModel(
            name='TaskResponsavelChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='alterado em')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
                ('new_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='novo responsável')),
                ('previous_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsável anterior')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_changes', to='activities.task', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'alteração de responsável',
                'verbose_name_plural': 'alterações de responsável',
                'ordering': ['-changed_at'],
            },
        ),
    ]
