# Generated by Django 5.2.17 on 2026-09-30 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_task_responsavel_not_null'),
        ('core', '0010_remove_site_company_site_client'),
        ('processes', '0002_processstep_default_responsavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='process_step',
            field=models.ForeignKey(blank=True, help_text='Etapa do processo que gerou esta tarefa (Regras 12 §16). Vazio nas tarefas criadas manualmente. Uma etapa gera no máximo uma tarefa por atividade.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='processes.processstep', verbose_name='etapa do processo'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('process_step__isnull', False)), fields=('activity', 'process_step'), name='unique_task_per_activity_process_step'),
        ),
    ]
