# Generated by Django 5.2.17 on 2026-09-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_task_process_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='logged_at',
            field=models.DateTimeField(blank=True, help_text='Quando o sistema soube do período (hora do servidor). `started_at`/`ended_at` dizem quando o trabalho aconteceu; este campo, quando foi informado (Regras 04 §214).', null=True, verbose_name='informado em'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='manual_reason',
            field=models.CharField(blank=True, choices=[('ESQUECI_INICIAR', 'Esqueci de iniciar'), ('FORA_DA_LPS', 'Trabalhei fora da LPS'), ('AJUSTE_PERIODO', 'Ajuste do período'), ('OUTRO', 'Outro')], max_length=16, verbose_name='motivo'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='comentário'),
        ),
    ]
