# Generated by Django 5.2.17 on 2026-09-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_trabalho_informado_depois'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='external_requester',
            field=models.CharField(blank=True, help_text='Nome de quem pediu a demanda fora da organização (cliente, fornecedor etc.) — texto livre, não é um cadastro. Distinto de `requested_by`, que é alguém da própria equipe.', max_length=150, verbose_name='solicitante externo'),
        ),
        migrations.AddField(
            model_name='activity',
            name='files_location',
            field=models.CharField(blank=True, help_text='Link (Drive, OneDrive...) ou caminho de rede/pasta dos arquivos da atividade. A LPS não guarda o arquivo: só aponta onde ele está.', max_length=500, verbose_name='link / caminho dos arquivos'),
        ),
    ]
