# Generated by Django 5.2.17 on 2026-10-01 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_solicitante_externo_e_local_dos_arquivos'),
        ('core', '0011_atividade_vira_demanda_nos_rotulos'),
        ('processes', '0002_processstep_default_responsavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_activities', 'Pode visualizar todas as demandas da organização'), ('can_change_owner', 'Pode alterar o dono da demanda'), ('can_reopen_activity', 'Pode reabrir demanda concluída'), ('can_cancel_activity', 'Pode cancelar demanda')], 'verbose_name': 'demanda', 'verbose_name_plural': 'demandas'},
        ),
        migrations.AlterModelOptions(
            name='activityattachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'anexo da demanda', 'verbose_name_plural': 'anexos da demanda'},
        ),
        migrations.AlterModelOptions(
            name='activitymessage',
            options={'ordering': ['created_at'], 'verbose_name': 'mensagem da demanda', 'verbose_name_plural': 'mensagens da demanda'},
        ),
        migrations.AlterModelOptions(
            name='activitypendency',
            options={'ordering': ['-opened_at'], 'verbose_name': 'pendência da demanda', 'verbose_name_plural': 'pendências da demanda'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='code',
            field=models.CharField(blank=True, editable=False, help_text='Gerado automaticamente ao salvar. Identifica a demanda e a pasta de anexos.', max_length=20, null=True, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='files_location',
            field=models.CharField(blank=True, help_text='Link (Drive, OneDrive...) ou caminho de rede/pasta dos arquivos da demanda. A LPS não guarda o arquivo: só aponta onde ele está.', max_length=500, verbose_name='link / caminho dos arquivos'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Responsável único pelo acompanhamento até a resolução (Regras 01 §6.1). Só pode ficar em branco enquanto a demanda é um rascunho.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities_owned', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='process_version',
            field=models.ForeignKey(blank=True, help_text='Vínculo travado no momento da criação — publicar nova versão não altera demandas antigas (Regras 11 §19).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='processes.processversion', verbose_name='versão do processo aplicada'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Setor para quem a demanda é endereçada — distinto do setor de cada tarefa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designated_activities', to='core.sector', verbose_name='grupo designado'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Camada visual configuravel; nao altera o status operacional da demanda.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.activitystage', verbose_name='estagio'),
        ),
        migrations.AlterField(
            model_name='activityattachment',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='activities.activity', verbose_name='demanda'),
        ),
        migrations.AlterField(
            model_name='activitymessage',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='activities.activity', verbose_name='demanda'),
        ),
        migrations.AlterField(
            model_name='activitypendency',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencies', to='activities.activity', verbose_name='demanda'),
        ),
        migrations.AlterField(
            model_name='ownerchangelog',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_changes', to='activities.activity', verbose_name='demanda'),
        ),
        migrations.AlterField(
            model_name='task',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='activities.activity', verbose_name='demanda'),
        ),
        migrations.AlterField(
            model_name='task',
            name='process_step',
            field=models.ForeignKey(blank=True, help_text='Etapa do processo que gerou esta tarefa (Regras 12 §16). Vazio nas tarefas criadas manualmente. Uma etapa gera no máximo uma tarefa por demanda.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='processes.processstep', verbose_name='etapa do processo'),
        ),
    ]
