# Generated by Django 5.2.17 on 2026-10-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0020_codigo_da_demanda"),
        ("core", "0012_sector_scoped_stages_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="condition",
            field=models.ForeignKey(blank=True, help_text="Leitura manual do trabalho; nunca altera o status operacional da demanda.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="activities", to="core.workflowstatus", verbose_name="condição"),
        ),
        migrations.AddField(
            model_name="task",
            name="condition",
            field=models.ForeignKey(blank=True, help_text="Leitura manual do trabalho; nunca altera o status operacional da tarefa.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tasks", to="core.workflowstatus", verbose_name="condição"),
        ),
    ]
