# Generated by Django 5.2.17 on 2026-10-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_activity_task_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=8, verbose_name='prioridade'),
        ),
    ]
