# Generated by Django 5.2.17 on 2026-10-02

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0022_task_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitymessage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="activities.activitymessage",
                verbose_name="mensagem de origem",
            ),
        ),
        migrations.AddField(
            model_name="activitymessage",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("ALL", "Todas as pessoas com acesso"),
                    ("PARTICIPANTS", "Somente participantes"),
                    ("SECTOR", "Somente meu setor"),
                ],
                default="ALL",
                max_length=14,
                verbose_name="visibilidade",
            ),
        ),
        migrations.AddField(
            model_name="activityattachment",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attachments",
                to="activities.activitymessage",
                verbose_name="mensagem",
            ),
        ),
        migrations.CreateModel(
            name="ActivityMessageReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("emoji", models.CharField(max_length=12, verbose_name="reação")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="reagiu em")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="activities.activitymessage",
                        verbose_name="mensagem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_message_reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "reação de mensagem da demanda",
                "verbose_name_plural": "reações de mensagens da demanda",
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "user", "emoji"),
                        name="unique_activity_message_reaction",
                    ),
                ],
            },
        ),
    ]
