# Generated by Django 5.0.14 on 2026-09-06 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('demands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default='ABERTO', max_length=12, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('cancelled_reason', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('demand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='demands.demand', verbose_name='demanda de origem')),
            ],
            options={
                'verbose_name': 'processo',
                'verbose_name_plural': 'processos',
                'permissions': [('can_create_process', 'Pode criar processo'), ('can_cancel_process', 'Pode cancelar processo'), ('can_view_all_processes', 'Pode visualizar todos os processos'), ('can_view_dashboard', 'Pode visualizar o dashboard')],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='ordem')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('priority', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='prioridade')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('EM_REVISAO', 'Em revisão'), ('CONCLUIDA', 'Concluída'), ('BLOQUEADA', 'Bloqueada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=12, verbose_name='status')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='assumida em')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='liberada em')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='prazo')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciada em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('observations', models.TextField(blank=True, verbose_name='observações')),
                ('condition', models.CharField(blank=True, max_length=255, verbose_name='condição (reservado)')),
                ('overdue_notified_at', models.DateTimeField(blank=True, help_text='Evita reenviar a notificação/e-mail de atraso a cada verificação.', null=True, verbose_name='notificação de atraso enviada em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps_assumed', to=settings.AUTH_USER_MODEL, verbose_name='assumida por')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.processstep', verbose_name='próxima etapa (reservado)')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.process', verbose_name='processo')),
                ('responsible_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auth.group', verbose_name='grupo responsável')),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
                'ordering': ['order'],
                'permissions': [('can_claim_any_activity', 'Pode assumir qualquer atividade, fora do próprio grupo'), ('can_override_assignment', 'Pode concluir atividade que não assumiu'), ('can_reopen_activity', 'Pode reabrir atividade concluída'), ('can_edit_workflow', 'Pode editar a estrutura do workflow de um processo'), ('can_block_activity', 'Pode bloquear/desbloquear atividade')],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='arquivo')),
                ('category', models.CharField(choices=[('DOCUMENTO', 'Documento'), ('PROPOSTA', 'Proposta'), ('PLANILHA', 'Planilha'), ('FOTO', 'Foto'), ('OUTRO', 'Outro')], default='OUTRO', max_length=12, verbose_name='categoria')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflows.process', verbose_name='processo')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='workflows.processstep', verbose_name='atividade')),
            ],
            options={
                'verbose_name': 'anexo',
                'verbose_name_plural': 'anexos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'template de processo',
                'verbose_name_plural': 'templates de processo',
                'permissions': [('can_manage_templates', 'Pode gerenciar templates de processo')],
            },
        ),
        migrations.AddField(
            model_name='process',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='workflows.processtemplate', verbose_name='template'),
        ),
        migrations.CreateModel(
            name='ProcessTemplateStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='ordem')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('default_deadline_days', models.PositiveIntegerField(help_text='Dias corridos a partir da liberação da etapa.', verbose_name='prazo padrão (dias corridos)')),
                ('default_priority', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='prioridade padrão')),
                ('condition', models.CharField(blank=True, max_length=255, verbose_name='condição (reservado)')),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_steps', to='workflows.processtemplatestep', verbose_name='próxima etapa (reservado)')),
                ('responsible_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auth.group', verbose_name='grupo responsável')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.processtemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'etapa do template',
                'verbose_name_plural': 'etapas do template',
                'ordering': ['order'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.AddField(
            model_name='processstep',
            name='template_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.processtemplatestep', verbose_name='etapa do template de origem'),
        ),
        migrations.AlterUniqueTogether(
            name='processstep',
            unique_together={('process', 'order')},
        ),
    ]
