# Generated by Django 5.2.17 on 2026-09-16 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='critério')),
                ('is_required', models.BooleanField(default=True, verbose_name='obrigatório')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'critério de aceite',
                'verbose_name_plural': 'critérios de aceite',
                'ordering': ['version', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('input_type', models.CharField(choices=[('TEXTO', 'Texto'), ('ARQUIVO', 'Arquivo'), ('DATA', 'Data'), ('NUMERO', 'Número'), ('LINK', 'Link'), ('SELECAO', 'Seleção')], default='TEXTO', max_length=8, verbose_name='tipo')),
                ('is_required', models.BooleanField(default=True, verbose_name='obrigatório')),
                ('source', models.CharField(blank=True, choices=[('SOLICITANTE', 'Solicitante'), ('EXECUTOR', 'Executor'), ('TERCEIRO', 'Terceiro')], max_length=11, verbose_name='origem')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='ajuda de preenchimento')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'input do processo',
                'verbose_name_plural': 'inputs do processo',
                'ordering': ['version', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_types', to='core.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'tipo de atividade',
                'verbose_name_plural': 'tipos de atividade',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Inativar impede novas aplicações, mas preserva o histórico (Regras 05 §22).', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='processes.activitytype', verbose_name='tipo de atividade')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='core.company', verbose_name='empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='core.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'processo',
                'verbose_name_plural': 'processos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityCriterionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_met', models.BooleanField(default=False, verbose_name='atendido')),
                ('met_at', models.DateTimeField(blank=True, null=True, verbose_name='atendido em')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_checks', to='activities.activity', verbose_name='atividade')),
                ('met_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('process_criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='processes.processcriterion', verbose_name='critério de aceite')),
            ],
            options={
                'verbose_name': 'critério verificado na atividade',
                'verbose_name_plural': 'critérios verificados na atividade',
                'ordering': ['activity', 'process_criterion__order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityInputValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='valor')),
                ('is_received', models.BooleanField(default=False, verbose_name='recebido')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='recebido em')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_values', to='activities.activity', verbose_name='atividade')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('process_input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='processes.processinput', verbose_name='input do processo')),
            ],
            options={
                'verbose_name': 'input recebido na atividade',
                'verbose_name_plural': 'inputs recebidos na atividade',
                'ordering': ['activity', 'process_input__order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='versão')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado'), ('SUBSTITUIDO', 'Substituído')], default='RASCUNHO', max_length=11, verbose_name='status')),
                ('output_description', models.TextField(blank=True, help_text="Resultado verificável, não a ação (Regras 11 §11) — ex.: 'Proposta comercial pronta para envio'.", verbose_name='entrega esperada')),
                ('output_evidence_type', models.CharField(blank=True, choices=[('ARQUIVO', 'Arquivo'), ('LINK', 'Link'), ('CHECKLIST', 'Checklist'), ('CONFIRMACAO', 'Confirmação simples')], max_length=11, verbose_name='evidência do output')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicada em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='processes.process', verbose_name='processo')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='publicada por')),
            ],
            options={
                'verbose_name': 'versão do processo',
                'verbose_name_plural': 'versões do processo',
                'ordering': ['process', '-number'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome da tarefa')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ordem')),
                ('depends_on_previous', models.BooleanField(default=True, help_text='Dependência simples e linear (Regras 11 §37) — sem regras condicionais.', verbose_name='depende da etapa anterior')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.sector', verbose_name='setor responsável')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='processes.processversion', verbose_name='versão do processo')),
            ],
            options={
                'verbose_name': 'etapa do fluxo padrão',
                'verbose_name_plural': 'etapas do fluxo padrão',
                'ordering': ['version', 'order'],
            },
        ),
        migrations.AddField(
            model_name='processinput',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='processes.processversion', verbose_name='versão do processo'),
        ),
        migrations.AddField(
            model_name='processcriterion',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='processes.processversion', verbose_name='versão do processo'),
        ),
        migrations.AddConstraint(
            model_name='activitytype',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_activity_type_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_process_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='activitycriterioncheck',
            constraint=models.UniqueConstraint(fields=('activity', 'process_criterion'), name='unique_criterion_check_per_activity'),
        ),
        migrations.AddConstraint(
            model_name='activityinputvalue',
            constraint=models.UniqueConstraint(fields=('activity', 'process_input'), name='unique_input_value_per_activity'),
        ),
        migrations.AddConstraint(
            model_name='processversion',
            constraint=models.UniqueConstraint(fields=('process', 'number'), name='unique_version_number_per_process'),
        ),
    ]
