# Generated by Django 5.2.17 on 2026-09-30 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='default_responsavel',
            field=models.ForeignKey(blank=True, help_text='Quem responde pela tarefa gerada por esta etapa. Opcional: sem ele, quem aplica o processo escolhe o responsável. Precisa ser da mesma organização; não precisa participar do setor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsável padrão'),
        ),
    ]
