# Generated by Django 5.2.17 on 2026-10-01 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_atividade_vira_demanda_nos_rotulos'),
        ('processes', '0002_processstep_default_responsavel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitycriterioncheck',
            options={'ordering': ['activity', 'process_criterion__order'], 'verbose_name': 'critério verificado na demanda', 'verbose_name_plural': 'critérios verificados na demanda'},
        ),
        migrations.AlterModelOptions(
            name='activityinputvalue',
            options={'ordering': ['activity', 'process_input__order'], 'verbose_name': 'input recebido na demanda', 'verbose_name_plural': 'inputs recebidos na demanda'},
        ),
        migrations.AlterModelOptions(
            name='activitytype',
            options={'ordering': ['name'], 'verbose_name': 'tipo de demanda', 'verbose_name_plural': 'tipos de demanda'},
        ),
        migrations.AlterField(
            model_name='activitycriterioncheck',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_checks', to='activities.activity', verbose_name='demanda'),
        ),
        migrations.AlterField(
            model_name='activityinputvalue',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_values', to='activities.activity', verbose_name='demanda'),
        ),
        migrations.AlterField(
            model_name='process',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='processes.activitytype', verbose_name='tipo de demanda'),
        ),
    ]
