# Generated by Django 5.2.17 on 2026-09-15 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('main_sector', models.ForeignKey(blank=True, help_text='Usado como padrão em filtros de telas do usuário (Regras 05 §29). Não limita os demais vínculos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sector', verbose_name='setor principal')),
                ('organization', models.ForeignKey(blank=True, help_text='Um usuário da LPS pertence a uma única organização (Regras 05 §7).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.organization', verbose_name='organização')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
        migrations.CreateModel(
            name='UserSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='desde')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='removido em')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='core.sector', verbose_name='setor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'participação em setor',
                'verbose_name_plural': 'participações em setores',
                'constraints': [models.UniqueConstraint(fields=('user', 'sector'), name='unique_active_user_sector')],
            },
        ),
    ]
