# Generated by Django 5.2.17 on 2026-09-15 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersector',
            options={'ordering': ['-joined_at'], 'verbose_name': 'participação em setor', 'verbose_name_plural': 'participações em setores'},
        ),
        migrations.RemoveConstraint(
            model_name='usersector',
            name='unique_active_user_sector',
        ),
        migrations.AddField(
            model_name='usersector',
            name='role',
            field=models.CharField(choices=[('MEMBRO', 'Membro'), ('GESTOR', 'Gestor')], default='MEMBRO', max_length=6, verbose_name='papel'),
        ),
        migrations.AddConstraint(
            model_name='usersector',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('user', 'sector'), name='unique_active_user_sector'),
        ),
    ]
