# Generated by Django 5.2.17 on 2026-10-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Ligado quando um administrador define uma senha provisória: a pessoa só segue depois de escolher a dela.', verbose_name='trocar a senha no próximo acesso'),
        ),
    ]
