# Generated by Django 5.0.14 on 2026-09-06 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(editable=False, max_length=30, unique=True, verbose_name='protocolo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de entrada')),
                ('communication_channel', models.CharField(choices=[('TELEFONE', 'Telefone'), ('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp'), ('PRESENCIAL', 'Presencial'), ('SITE', 'Site/Formulário'), ('OUTRO', 'Outro')], default='OUTRO', max_length=12, verbose_name='canal de origem')),
                ('client_name', models.CharField(max_length=200, verbose_name='empresa/cliente solicitante')),
                ('client_document', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('client_contact_name', models.CharField(blank=True, max_length=150, verbose_name='contato solicitante')),
                ('client_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='telefone do contato')),
                ('client_contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail do contato')),
                ('intermediary_name', models.CharField(blank=True, max_length=200, verbose_name='representante/intermediário')),
                ('final_client_name', models.CharField(blank=True, max_length=200, verbose_name='cliente final')),
                ('is_existing_client', models.BooleanField(default=False, verbose_name='já é cliente')),
                ('site_name', models.CharField(blank=True, max_length=200, verbose_name='empreendimento')),
                ('site_address', models.CharField(blank=True, max_length=255, verbose_name='endereço da obra')),
                ('site_city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('site_state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('site_type', models.CharField(blank=True, max_length=150, verbose_name='tipo de obra')),
                ('site_phase', models.CharField(blank=True, max_length=150, verbose_name='fase da obra')),
                ('request_summary', models.TextField(verbose_name='objeto solicitado')),
                ('disciplines_requested', models.TextField(blank=True, verbose_name='disciplinas solicitadas')),
                ('supply_materials', models.BooleanField(default=False, verbose_name='fornecimento de materiais')),
                ('supply_labor', models.BooleanField(default=False, verbose_name='fornecimento de mão de obra')),
                ('supply_equipment', models.BooleanField(default=False, verbose_name='fornecimento de equipamentos')),
                ('supply_project_development', models.BooleanField(default=False, verbose_name='desenvolvimento de projetos')),
                ('request_details', models.TextField(blank=True, verbose_name='detalhes adicionais da solicitação')),
                ('documentation_received', models.TextField(blank=True, help_text='Projetos, memoriais, planilhas, anexos, links externos.', verbose_name='documentação recebida')),
                ('documentation_missing', models.TextField(blank=True, verbose_name='documentos faltantes')),
                ('documentation_invalid', models.TextField(blank=True, verbose_name='arquivos inválidos/corrompidos')),
                ('project_level', models.CharField(blank=True, max_length=150, verbose_name='nível dos projetos recebidos')),
                ('disciplines_with_project', models.TextField(blank=True, verbose_name='disciplinas com projeto')),
                ('disciplines_without_project', models.TextField(blank=True, verbose_name='disciplinas sem projeto')),
                ('information_completeness', models.CharField(blank=True, choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], max_length=10, verbose_name='documentação completa/parcial')),
                ('conflicts_identified', models.TextField(blank=True, verbose_name='conflitos identificados')),
                ('confidence_notes', models.TextField(blank=True, verbose_name='nível de confiança da entrada')),
                ('confirmation_deadline', models.DateTimeField(blank=True, null=True, verbose_name='prazo para confirmar participação')),
                ('questions_deadline', models.DateTimeField(blank=True, null=True, verbose_name='prazo para envio de dúvidas')),
                ('proposal_deadline', models.DateTimeField(blank=True, null=True, verbose_name='prazo para a proposta')),
                ('expected_construction_start', models.DateField(blank=True, null=True, verbose_name='início previsto da obra')),
                ('expected_execution_duration', models.CharField(blank=True, max_length=100, verbose_name='prazo previsto de execução')),
                ('contracting_modality', models.CharField(blank=True, max_length=150, verbose_name='modalidade de contratação')),
                ('payment_terms', models.CharField(blank=True, max_length=200, verbose_name='forma de pagamento')),
                ('direct_billing', models.BooleanField(default=False, verbose_name='faturamento direto')),
                ('retentions_notes', models.CharField(blank=True, max_length=255, verbose_name='retenções')),
                ('guarantees_notes', models.CharField(blank=True, max_length=255, verbose_name='garantias/seguros')),
                ('specific_taxes_notes', models.CharField(blank=True, max_length=255, verbose_name='impostos específicos')),
                ('proposal_validity_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='validade da proposta (dias)')),
                ('price_adjustment_notes', models.CharField(blank=True, max_length=255, verbose_name='reajuste')),
                ('deliverable_technical_proposal', models.BooleanField(default=False, verbose_name='proposta técnica')),
                ('deliverable_commercial_proposal', models.BooleanField(default=False, verbose_name='proposta comercial')),
                ('deliverable_client_spreadsheet', models.BooleanField(default=False, verbose_name='planilha do cliente')),
                ('deliverable_wbs', models.BooleanField(default=False, verbose_name='EAP/plano de contas')),
                ('deliverable_schedule', models.BooleanField(default=False, verbose_name='cronograma')),
                ('deliverable_histogram', models.BooleanField(default=False, verbose_name='histograma')),
                ('deliverable_other_notes', models.CharField(blank=True, max_length=255, verbose_name='outros documentos')),
                ('reference_email', models.CharField(blank=True, max_length=255, verbose_name='e-mail de referência')),
                ('verbal_information_notes', models.TextField(blank=True, verbose_name='informações recebidas verbalmente')),
                ('whatsapp_information_notes', models.TextField(blank=True, verbose_name='informações recebidas por WhatsApp')),
                ('technical_contact_notes', models.CharField(blank=True, max_length=255, verbose_name='contato para dúvidas técnicas')),
                ('proposal_recipient', models.CharField(blank=True, max_length=255, verbose_name='destinatário da proposta')),
                ('requires_intermediary_approval', models.BooleanField(default=False, verbose_name='necessidade de aprovação do representante')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands_created', to=settings.AUTH_USER_MODEL, verbose_name='responsável interno')),
            ],
            options={
                'verbose_name': 'demanda',
                'verbose_name_plural': 'demandas',
                'ordering': ['-created_at'],
                'permissions': [('can_qualify_demand', 'Pode qualificar/decidir sobre a demanda'), ('can_view_all_demands', 'Pode visualizar todas as demandas')],
            },
        ),
        migrations.CreateModel(
            name='DemandDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONVERTIDA', 'Convertida em processo'), ('RECUSADA', 'Recusada'), ('AGUARDANDO_INFO', 'Aguardando informações')], default='PENDENTE', max_length=16, verbose_name='decisão')),
                ('pending_items', models.TextField(blank=True, verbose_name='pendências')),
                ('pending_impact_notes', models.TextField(blank=True, verbose_name='impacto no orçamento')),
                ('pending_disciplines_affected', models.CharField(blank=True, max_length=255, verbose_name='disciplina afetada')),
                ('can_budget', models.BooleanField(blank=True, null=True, verbose_name='podemos orçar?')),
                ('can_budget_partially', models.BooleanField(blank=True, null=True, verbose_name='podemos orçar parcialmente?')),
                ('risks_notes', models.TextField(blank=True, verbose_name='principais riscos')),
                ('deadline_is_viable', models.BooleanField(blank=True, null=True, verbose_name='prazo é viável?')),
                ('decision_notes', models.TextField(blank=True, verbose_name='observações da decisão')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='data da decisão')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='decidido por')),
                ('demand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='demands.demand', verbose_name='demanda')),
            ],
            options={
                'verbose_name': 'decisão de demanda',
                'verbose_name_plural': 'decisões de demanda',
            },
        ),
    ]
