# Generated by Django 5.0.14 on 2026-09-06 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demands', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanddecision',
            name='resulting_process',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_decision', to='workflows.process', verbose_name='processo gerado'),
        ),
    ]
