# Generated by Django 5.0.14 on 2026-09-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('CLAIM', 'Assumida'), ('COMPLETE', 'Concluída'), ('REOPEN', 'Reaberta'), ('BLOCK', 'Bloqueada'), ('UNBLOCK', 'Desbloqueada'), ('CANCEL', 'Cancelada'), ('FINALIZE', 'Finalizada'), ('DECIDE', 'Decisão registrada')], max_length=12, verbose_name='ação')),
                ('field_name', models.CharField(blank=True, max_length=50, verbose_name='campo alterado')),
                ('old_value', models.TextField(blank=True, verbose_name='valor anterior')),
                ('new_value', models.TextField(blank=True, verbose_name='novo valor')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='data/hora')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-timestamp'],
            },
        ),
    ]
