# Generated by Django 5.2.17 on 2026-09-15 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('OWNER_CHANGED', 'Dono alterado'), ('TASK_CREATED', 'Tarefa criada'), ('EXECUTOR_ADDED', 'Executor incluído'), ('EXECUTOR_REMOVED', 'Executor removido'), ('SESSION_STARTED', 'Sessão iniciada'), ('SESSION_PAUSED', 'Sessão pausada'), ('SESSION_RESUMED', 'Sessão retomada'), ('SECTOR_MOVED', 'Movida de setor'), ('RETURNED', 'Devolvida'), ('QUEUE_POSITION_CHANGED', 'Posição na fila alterada'), ('DEADLINE_PROPOSED', 'Prazo proposto'), ('DEADLINE_ACCEPTED', 'Prazo aceito'), ('DEADLINE_REJECTED', 'Prazo recusado'), ('CONFLICT_OPENED', 'Conflito de prazo aberto'), ('CONFLICT_RESOLVED', 'Conflito de prazo resolvido'), ('BLOCK', 'Bloqueada'), ('UNBLOCK', 'Desbloqueada'), ('COMPLETE', 'Concluída'), ('REOPEN', 'Reaberta'), ('CANCEL', 'Cancelada')], max_length=24, verbose_name='ação')),
                ('field_name', models.CharField(blank=True, max_length=50, verbose_name='campo alterado')),
                ('old_value', models.TextField(blank=True, verbose_name='valor anterior')),
                ('new_value', models.TextField(blank=True, verbose_name='novo valor')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='data/hora')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='activities.activity', verbose_name='atividade')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='activities.task', verbose_name='tarefa')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['activity', 'timestamp'], name='audit_audit_activit_8967f3_idx'), models.Index(fields=['task', 'timestamp'], name='audit_audit_task_id_1124e3_idx')],
            },
        ),
    ]
