# Generated by Django 5.0.14 on 2026-09-06 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='demand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='demands.demand', verbose_name='demanda'),
        ),
    ]
