# Generated by Django 5.2.17 on 2026-09-15 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='Preenchido em eventos de segurança, que não se referem a uma atividade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='usuário afetado'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('OWNER_CHANGED', 'Dono alterado'), ('TASK_CREATED', 'Tarefa criada'), ('EXECUTOR_ADDED', 'Executor incluído'), ('EXECUTOR_REMOVED', 'Executor removido'), ('SESSION_STARTED', 'Sessão iniciada'), ('SESSION_PAUSED', 'Sessão pausada'), ('SESSION_RESUMED', 'Sessão retomada'), ('SECTOR_MOVED', 'Movida de setor'), ('RETURNED', 'Devolvida'), ('QUEUE_POSITION_CHANGED', 'Posição na fila alterada'), ('DEADLINE_PROPOSED', 'Prazo proposto'), ('DEADLINE_ACCEPTED', 'Prazo aceito'), ('DEADLINE_REJECTED', 'Prazo recusado'), ('CONFLICT_OPENED', 'Conflito de prazo aberto'), ('CONFLICT_RESOLVED', 'Conflito de prazo resolvido'), ('BLOCK', 'Bloqueada'), ('UNBLOCK', 'Desbloqueada'), ('COMPLETE', 'Concluída'), ('REOPEN', 'Reaberta'), ('CANCEL', 'Cancelada'), ('PROFILE_CREATED', 'Perfil criado'), ('PROFILE_UPDATED', 'Perfil alterado'), ('PROFILE_ACTIONS_CHANGED', 'Ações do perfil alteradas'), ('PROFILE_ASSIGNED', 'Perfil atribuído'), ('PROFILE_REVOKED', 'Perfil removido'), ('ACTION_GRANTED', 'Concessão direta registrada'), ('ACTION_REVOKED', 'Concessão direta removida'), ('SECTORS_CHANGED', 'Setores do usuário alterados')], max_length=24, verbose_name='ação'),
        ),
    ]
