# Generated by Django 5.0.14 on 2026-09-06 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0002_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='workflows.process', verbose_name='processo'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='workflows.processstep', verbose_name='atividade'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['process', 'timestamp'], name='audit_audit_process_6c914d_idx'),
        ),
    ]
