# Generated by Django 5.2.17 on 2026-09-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_target_user_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('OWNER_CHANGED', 'Dono alterado'), ('TASK_CREATED', 'Tarefa criada'), ('EXECUTOR_ADDED', 'Executor incluído'), ('EXECUTOR_REMOVED', 'Executor removido'), ('ASSIGNMENT_CREATED', 'Atribuição criada, aguardando aceite'), ('ASSIGNMENT_ACCEPTED', 'Atribuição aceita'), ('ASSIGNMENT_REJECTED', 'Atribuição recusada'), ('SESSION_STARTED', 'Sessão iniciada'), ('SESSION_PAUSED', 'Sessão pausada'), ('SESSION_RESUMED', 'Sessão retomada'), ('SECTOR_MOVED', 'Movida de setor'), ('RETURNED', 'Devolvida'), ('QUEUE_POSITION_CHANGED', 'Posição na fila alterada'), ('DEADLINE_PROPOSED', 'Prazo proposto'), ('DEADLINE_ACCEPTED', 'Prazo aceito'), ('DEADLINE_REJECTED', 'Prazo recusado'), ('CONFLICT_OPENED', 'Conflito de prazo aberto'), ('CONFLICT_RESOLVED', 'Conflito de prazo resolvido'), ('BLOCK', 'Bloqueada'), ('UNBLOCK', 'Desbloqueada'), ('COMPLETE', 'Concluída'), ('REOPEN', 'Reaberta'), ('CANCEL', 'Cancelada'), ('PROFILE_CREATED', 'Perfil criado'), ('PROFILE_UPDATED', 'Perfil alterado'), ('PROFILE_ACTIONS_CHANGED', 'Ações do perfil alteradas'), ('PROFILE_ASSIGNED', 'Perfil atribuído'), ('PROFILE_REVOKED', 'Perfil removido'), ('ACTION_GRANTED', 'Concessão direta registrada'), ('ACTION_REVOKED', 'Concessão direta removida'), ('SECTORS_CHANGED', 'Setores do usuário alterados')], max_length=24, verbose_name='ação'),
        ),
    ]
