# Generated by Django 5.2.17 on 2026-10-01 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_atividade_vira_demanda_nos_rotulos'),
        ('audit', '0008_trabalho_informado_depois'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='activities.activity', verbose_name='demanda'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='Preenchido em eventos de segurança, que não se referem a uma demanda.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='usuário afetado'),
        ),
    ]
