# Generated by Django 5.2.17 on 2026-10-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_visualizacoes_de_quadro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('OWNER_CHANGED', 'Dono alterado'), ('RESPONSAVEL_CHANGED', 'Responsável alterado'), ('TASK_CREATED', 'Tarefa criada'), ('EXECUTOR_ADDED', 'Executor incluído'), ('EXECUTOR_REMOVED', 'Executor removido'), ('ASSIGNMENT_CREATED', 'Atribuição criada, aguardando aceite'), ('ASSIGNMENT_ACCEPTED', 'Atribuição aceita'), ('ASSIGNMENT_REJECTED', 'Atribuição recusada'), ('SESSION_STARTED', 'Sessão iniciada'), ('SESSION_PAUSED', 'Sessão pausada'), ('SESSION_RESUMED', 'Sessão retomada'), ('SECTOR_MOVED', 'Movida de setor'), ('RETURNED', 'Devolvida'), ('QUEUE_POSITION_CHANGED', 'Posição na fila alterada'), ('DEADLINE_PROPOSED', 'Prazo proposto'), ('DEADLINE_ACCEPTED', 'Prazo aceito'), ('DEADLINE_REJECTED', 'Prazo recusado'), ('CONFLICT_OPENED', 'Conflito de prazo aberto'), ('CONFLICT_RESOLVED', 'Conflito de prazo resolvido'), ('BLOCK', 'Bloqueada'), ('UNBLOCK', 'Desbloqueada'), ('COMPLETE', 'Concluída'), ('REOPEN', 'Reaberta'), ('CANCEL', 'Cancelada'), ('PENDENCY_OPENED', 'Marcada como pendente'), ('PENDENCY_APPROVED', 'Pendência aprovada'), ('PROCESS_APPLIED', 'Processo aplicado'), ('INPUT_UPDATED', 'Input atualizado'), ('CRITERION_UPDATED', 'Critério de aceite atualizado'), ('TASK_RELEASED', 'Tarefa liberada para a fila'), ('RETROACTIVE_LOGGED', 'Trabalho informado depois'), ('PROFILE_CREATED', 'Perfil criado'), ('PROFILE_UPDATED', 'Perfil alterado'), ('PROFILE_ACTIONS_CHANGED', 'Ações do perfil alteradas'), ('PROFILE_ASSIGNED', 'Perfil atribuído'), ('PROFILE_REVOKED', 'Perfil removido'), ('ACTION_GRANTED', 'Concessão direta registrada'), ('ACTION_REVOKED', 'Concessão direta removida'), ('SECTORS_CHANGED', 'Setores do usuário alterados'), ('USER_CREATED', 'Usuário criado'), ('PASSWORD_RESET', 'Senha redefinida'), ('USER_UPDATED', 'Usuário alterado'), ('USER_INVITED', 'Convite enviado'), ('SUPERUSER_CHANGED', 'Super usuário alterado'), ('BOARD_CREATED', 'Quadro criado'), ('BOARD_UPDATED', 'Quadro alterado'), ('BOARD_DELETED', 'Quadro excluído'), ('BOARD_GROUP_CREATED', 'Grupo criado'), ('BOARD_GROUP_UPDATED', 'Grupo alterado'), ('BOARD_GROUP_MOVED', 'Grupo movido'), ('BOARD_GROUP_DELETED', 'Grupo excluído'), ('BOARD_COLUMN_CREATED', 'Coluna criada'), ('BOARD_COLUMN_UPDATED', 'Coluna alterada'), ('BOARD_COLUMN_MOVED', 'Coluna movida'), ('BOARD_COLUMN_RESIZED', 'Coluna redimensionada'), ('BOARD_COLUMN_DELETED', 'Coluna excluída'), ('BOARD_ITEM_CREATED', 'Item criado'), ('BOARD_ITEM_UPDATED', 'Item alterado'), ('BOARD_ITEM_MOVED', 'Item movido'), ('BOARD_ITEM_DELETED', 'Item excluído'), ('BOARD_CELL_UPDATED', 'Célula alterada'), ('BOARD_VIEW_CREATED', 'Visualização criada'), ('BOARD_VIEW_UPDATED', 'Visualização alterada'), ('BOARD_VIEW_DELETED', 'Visualização excluída')], max_length=24, verbose_name='ação'),
        ),
    ]
