# Generated by Django 5.2.17 on 2026-10-02 02:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_sector_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('item_label', models.CharField(default='Elemento', help_text='Como a primeira coluna (o nome de cada item) se chama neste quadro, ex.: Obra, Contrato.', max_length=60, verbose_name='título da coluna principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boards_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='core.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'quadro',
                'verbose_name_plural': 'quadros',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BoardCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, verbose_name='texto')),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, verbose_name='número')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='data')),
                ('value_datetime', models.DateTimeField(blank=True, null=True, verbose_name='data e hora')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='sim/não')),
                ('value_json', models.JSONField(blank=True, default=dict, verbose_name='dados extras')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterada em')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_cells_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterada por')),
            ],
            options={
                'verbose_name': 'célula do quadro',
                'verbose_name_plural': 'células do quadro',
            },
        ),
        migrations.CreateModel(
            name='BoardCellUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posição')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_values', to='boards.boardcell', verbose_name='célula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_cell_values', to=settings.AUTH_USER_MODEL, verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'pessoa da célula',
                'verbose_name_plural': 'pessoas da célula',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('type', models.CharField(choices=[('TEXT', 'Texto'), ('NUMBER', 'Número'), ('CURRENCY', 'Moeda'), ('DATE', 'Data'), ('PERSON', 'Pessoa'), ('STATUS', 'Status'), ('DROPDOWN', 'Lista suspensa'), ('CHECKBOX', 'Sinal de confirmação'), ('FILE', 'Arquivo'), ('TIMELINE', 'Cronograma'), ('PRIORITY', 'Prioridade'), ('CONFIRMATION', 'Confirmação'), ('RELATION', 'Conectar quadros'), ('FORMULA', 'Fórmula'), ('AI_EXTRACT', 'Extração por IA')], max_length=32, verbose_name='tipo')),
                ('position', models.DecimalField(decimal_places=6, default=Decimal('1000'), max_digits=20, verbose_name='posição')),
                ('width', models.PositiveIntegerField(default=160, validators=[django.core.validators.MinValueValidator(96), django.core.validators.MaxValueValidator(640)], verbose_name='largura')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='configuração do tipo')),
                ('is_required', models.BooleanField(default=False, verbose_name='obrigatória')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visível')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterada em')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='boards.board', verbose_name='quadro')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_columns_created', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
            ],
            options={
                'verbose_name': 'coluna do quadro',
                'verbose_name_plural': 'colunas do quadro',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='boardcell',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cells', to='boards.boardcolumn', verbose_name='coluna'),
        ),
        migrations.CreateModel(
            name='BoardColumnOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='rótulo')),
                ('color', models.CharField(default='#C4C4C4', max_length=7, verbose_name='cor')),
                ('position', models.DecimalField(decimal_places=6, default=Decimal('1000'), max_digits=20, verbose_name='posição')),
                ('is_default', models.BooleanField(default=False, verbose_name='etiqueta padrão')),
                ('is_done', models.BooleanField(default=False, verbose_name='representa conclusão')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='boards.boardcolumn', verbose_name='coluna')),
            ],
            options={
                'verbose_name': 'etiqueta da coluna',
                'verbose_name_plural': 'etiquetas da coluna',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BoardCellOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posição')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_values', to='boards.boardcell', verbose_name='célula')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cell_values', to='boards.boardcolumnoption', verbose_name='etiqueta')),
            ],
            options={
                'verbose_name': 'etiqueta da célula',
                'verbose_name_plural': 'etiquetas da célula',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BoardGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('color', models.CharField(default='#579BFC', max_length=7, verbose_name='cor')),
                ('position', models.DecimalField(decimal_places=6, default=Decimal('1000'), max_digits=20, verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='boards.board', verbose_name='quadro')),
            ],
            options={
                'verbose_name': 'grupo do quadro',
                'verbose_name_plural': 'grupos do quadro',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='nome')),
                ('position', models.DecimalField(decimal_places=6, default=Decimal('1000'), max_digits=20, verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boards.board', verbose_name='quadro')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_items_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='boards.boardgroup', verbose_name='grupo')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_items_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'item do quadro',
                'verbose_name_plural': 'itens do quadro',
                'ordering': ['group__position', 'position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='boardcell',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='boards.boarditem', verbose_name='item'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['organization', 'is_active'], name='boards_boar_organiz_90eff7_idx'),
        ),
        migrations.AddConstraint(
            model_name='boardcelluser',
            constraint=models.UniqueConstraint(fields=('cell', 'user'), name='uniq_board_cell_user'),
        ),
        migrations.AddIndex(
            model_name='boardcolumn',
            index=models.Index(fields=['board', 'is_active', 'position'], name='boards_boar_board_i_92fe66_idx'),
        ),
        migrations.AddIndex(
            model_name='boardcolumnoption',
            index=models.Index(fields=['column', 'is_active', 'position'], name='boards_boar_column__71a901_idx'),
        ),
        migrations.AddConstraint(
            model_name='boardcelloption',
            constraint=models.UniqueConstraint(fields=('cell', 'option'), name='uniq_board_cell_option'),
        ),
        migrations.AddIndex(
            model_name='boardgroup',
            index=models.Index(fields=['board', 'is_active', 'position'], name='boards_boar_board_i_355156_idx'),
        ),
        migrations.AddIndex(
            model_name='boarditem',
            index=models.Index(fields=['board', 'group', 'is_active', 'position'], name='boards_boar_board_i_36219a_idx'),
        ),
        migrations.AddIndex(
            model_name='boardcell',
            index=models.Index(fields=['column', 'value_number'], name='boards_boar_column__52b921_idx'),
        ),
        migrations.AddIndex(
            model_name='boardcell',
            index=models.Index(fields=['column', 'value_date'], name='boards_boar_column__35edad_idx'),
        ),
        migrations.AddIndex(
            model_name='boardcell',
            index=models.Index(fields=['column', 'value_boolean'], name='boards_boar_column__2f5da5_idx'),
        ),
        migrations.AddConstraint(
            model_name='boardcell',
            constraint=models.UniqueConstraint(fields=('item', 'column'), name='uniq_board_cell_item_column'),
        ),
    ]
