# Generated by Django 5.2.17 on 2026-10-02 03:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('type', models.CharField(choices=[('KANBAN', 'Kanban')], default='KANBAN', max_length=16, verbose_name='tipo')),
                ('position', models.DecimalField(decimal_places=6, default=Decimal('1000'), max_digits=20, verbose_name='posição')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='configuração')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterada em')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='boards.board', verbose_name='quadro')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_views_created', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
            ],
            options={
                'verbose_name': 'visualização do quadro',
                'verbose_name_plural': 'visualizações do quadro',
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['board', 'is_active', 'position'], name='boards_boar_board_i_d6239c_idx')],
            },
        ),
    ]
