# Generated by Django 5.2.17 on 2026-10-02 03:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0022_task_priority'),
        ('boards', '0003_kanban_padrao_nos_quadros'),
        ('core', '0016_enumcolor_prioridade_da_tarefa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('DEMAND', 'Demandas'), ('TASK', 'Tarefas')], max_length=12, verbose_name='domínio')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_boards', to='core.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'quadro de domínio',
                'verbose_name_plural': 'quadros de domínio',
            },
        ),
        migrations.CreateModel(
            name='DomainBoardField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, verbose_name='chave')),
                ('label', models.CharField(max_length=120, verbose_name='rótulo')),
                ('type', models.CharField(choices=[('TEXT', 'Texto'), ('NUMBER', 'Número'), ('CURRENCY', 'Moeda'), ('DATETIME', 'Data e hora'), ('PERSON', 'Pessoa'), ('STAGE', 'Etapa'), ('SECTOR', 'Setor'), ('PRIORITY', 'Prioridade'), ('SELECT', 'Lista'), ('BOOLEAN', 'Confirmação'), ('CHECKLIST', 'Checklist'), ('RELATION', 'Relação')], max_length=16, verbose_name='tipo')),
                ('position', models.DecimalField(decimal_places=6, default=Decimal('1000'), max_digits=20, verbose_name='posição')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='configuração')),
                ('is_system', models.BooleanField(default=False, verbose_name='campo do sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='boards.domainboard', verbose_name='quadro')),
            ],
            options={
                'verbose_name': 'campo do quadro de domínio',
                'verbose_name_plural': 'campos do quadro de domínio',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DomainBoardChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='rótulo')),
                ('color', models.CharField(default='#94A3B8', max_length=7, verbose_name='cor')),
                ('position', models.DecimalField(decimal_places=6, default=Decimal('1000'), max_digits=20, verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='boards.domainboardfield', verbose_name='campo')),
            ],
            options={
                'verbose_name': 'opção do quadro de domínio',
                'verbose_name_plural': 'opções do quadro de domínio',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DomainBoardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('type', models.CharField(choices=[('TABLE', 'Quadro principal'), ('KANBAN', 'Kanban'), ('CALENDAR', 'Calendário')], max_length=12, verbose_name='tipo')),
                ('position', models.DecimalField(decimal_places=6, default=Decimal('1000'), max_digits=20, verbose_name='posição')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='configuração')),
                ('is_default', models.BooleanField(default=False, verbose_name='padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterada em')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='boards.domainboard', verbose_name='quadro')),
            ],
            options={
                'verbose_name': 'visualização de domínio',
                'verbose_name_plural': 'visualizações de domínio',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DomainBoardCardField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.DecimalField(decimal_places=6, default=Decimal('1000'), max_digits=20, verbose_name='posição')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visível')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_fields', to='boards.domainboardfield', verbose_name='campo')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_fields', to='boards.domainboardview', verbose_name='visualização')),
            ],
            options={
                'verbose_name': 'campo do cartão de domínio',
                'verbose_name_plural': 'campos do cartão de domínio',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DomainBoardViewColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.DecimalField(decimal_places=6, default=Decimal('1000'), max_digits=20, verbose_name='posição')),
                ('width', models.PositiveIntegerField(default=160, verbose_name='largura')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visível')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_columns', to='boards.domainboardfield', verbose_name='campo')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='boards.domainboardview', verbose_name='visualização')),
            ],
            options={
                'verbose_name': 'coluna da visualização de domínio',
                'verbose_name_plural': 'colunas da visualização de domínio',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DomainCustomValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='valor')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_values', to='activities.activity', verbose_name='demanda')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='boards.domainboardfield', verbose_name='campo')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_values', to='activities.task', verbose_name='tarefa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_board_values_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'valor customizado de domínio',
                'verbose_name_plural': 'valores customizados de domínio',
            },
        ),
        migrations.AddConstraint(
            model_name='domainboard',
            constraint=models.UniqueConstraint(fields=('organization', 'domain'), name='uniq_domain_board_org_domain'),
        ),
        migrations.AddConstraint(
            model_name='domainboardfield',
            constraint=models.UniqueConstraint(fields=('board', 'key'), name='uniq_domain_board_field_key'),
        ),
        migrations.AddConstraint(
            model_name='domainboardview',
            constraint=models.UniqueConstraint(fields=('board', 'name'), name='uniq_domain_board_view_name'),
        ),
        migrations.AddConstraint(
            model_name='domainboardcardfield',
            constraint=models.UniqueConstraint(fields=('view', 'field'), name='uniq_domain_card_field'),
        ),
        migrations.AddConstraint(
            model_name='domainboardviewcolumn',
            constraint=models.UniqueConstraint(fields=('view', 'field'), name='uniq_domain_view_column_field'),
        ),
        migrations.AddConstraint(
            model_name='domaincustomvalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activity__isnull', False), ('task__isnull', True)), models.Q(('activity__isnull', True), ('task__isnull', False)), _connector='OR'), name='domain_custom_value_one_target'),
        ),
        migrations.AddConstraint(
            model_name='domaincustomvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('activity__isnull', False)), fields=('field', 'activity'), name='uniq_domain_value_activity'),
        ),
        migrations.AddConstraint(
            model_name='domaincustomvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('task__isnull', False)), fields=('field', 'task'), name='uniq_domain_value_task'),
        ),
    ]
