# Generated by Django 5.2.17 on 2026-10-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_seed_domain_workboards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardview',
            name='type',
            field=models.CharField(choices=[('KANBAN', 'Kanban'), ('CALENDAR', 'Calendário')], default='KANBAN', max_length=16, verbose_name='tipo'),
        ),
    ]
