# Generated by Django 5.2.17 on 2026-09-15 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='chave')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'grupo de ações',
                'verbose_name_plural': 'grupos de ações',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Ex.: fila.reordenar', max_length=80, unique=True, verbose_name='chave')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Orienta confirmação na interface e auditoria reforçada; não concede nem remove acesso.', verbose_name='sensível')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='acessos.actiongroup', verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'ação',
                'verbose_name_plural': 'ações',
                'ordering': ['group__order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'perfil de acesso',
                'verbose_name_plural': 'perfis de acesso',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_actions', to='acessos.action', verbose_name='ação')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_actions', to='acessos.profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'ação do perfil',
                'verbose_name_plural': 'ações do perfil',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='actions',
            field=models.ManyToManyField(related_name='profiles', through='acessos.ProfileAction', to='acessos.action', verbose_name='ações'),
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ORGANIZACAO', 'Organização inteira'), ('EMPRESA', 'Empresa'), ('SETOR', 'Setor'), ('OBRA', 'Obra'), ('CENTRO_CUSTO', 'Centro de custo'), ('RELACIONAL', 'Relação com o objeto')], max_length=14, verbose_name='tipo')),
                ('relation', models.CharField(blank=True, choices=[('MINHAS_ATIVIDADES', 'Atividades das quais sou dono'), ('MINHAS_TAREFAS', 'Tarefas atribuídas a mim'), ('MEUS_SETORES', 'Setores dos quais participo'), ('SETORES_GERENCIADOS', 'Setores que gerencio')], max_length=24, verbose_name='relação')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='core.company', verbose_name='empresa')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='core.costcenter', verbose_name='centro de custo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='core.organization', verbose_name='organização')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='core.sector', verbose_name='setor')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='core.site', verbose_name='obra')),
            ],
            options={
                'verbose_name': 'escopo',
                'verbose_name_plural': 'escopos',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_grants', to='acessos.action', verbose_name='ação')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to='core.organization', verbose_name='organização')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_actions', to='acessos.scope', verbose_name='escopo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_actions', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'concessão direta',
                'verbose_name_plural': 'concessões diretas',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='core.organization', verbose_name='organização')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='acessos.profile', verbose_name='perfil')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='acessos.scope', verbose_name='escopo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_profiles', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil do usuário',
                'verbose_name_plural': 'perfis do usuário',
            },
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['group', 'is_active'], name='acessos_act_group_i_f79ce1_idx'),
        ),
        migrations.AddConstraint(
            model_name='profileaction',
            constraint=models.UniqueConstraint(fields=('profile', 'action'), name='unique_action_per_profile'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['organization', 'is_active'], name='acessos_pro_organiz_a7ec11_idx'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_profile_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='scope',
            index=models.Index(fields=['organization', 'type'], name='acessos_sco_organiz_aa8d53_idx'),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['user', 'is_active'], name='acessos_use_user_id_df9c23_idx'),
        ),
        migrations.AddConstraint(
            model_name='useraction',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'action', 'scope'), name='unique_active_user_action_scope'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'is_active'], name='acessos_use_user_id_f00433_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['profile', 'is_active'], name='acessos_use_profile_f341ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'profile', 'scope'), name='unique_active_user_profile_scope'),
        ),
    ]
