# Generated by Django 5.2.17 on 2026-10-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='relation',
            field=models.CharField(blank=True, choices=[('MINHAS_ATIVIDADES', 'Demandas das quais sou dono'), ('MINHAS_TAREFAS', 'Tarefas atribuídas a mim'), ('MEUS_SETORES', 'Setores dos quais participo'), ('SETORES_GERENCIADOS', 'Setores que gerencio')], max_length=24, verbose_name='relação'),
        ),
    ]
