# Generated by Django 5.0.14 on 2026-09-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STEP_RELEASED', 'Atividade liberada'), ('STEP_OVERDUE', 'Atividade atrasada'), ('STEP_CLAIMED', 'Atividade assumida'), ('STEP_COMPLETED', 'Atividade concluída'), ('STEP_REOPENED', 'Atividade reaberta'), ('STEP_BLOCKED', 'Atividade bloqueada'), ('STEP_CANCELLED', 'Atividade cancelada'), ('PROCESS_CREATED', 'Processo criado'), ('PROCESS_CANCELLED', 'Processo cancelado'), ('PROCESS_FINALIZED', 'Processo finalizado')], max_length=20, verbose_name='tipo')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('message', models.CharField(max_length=255, verbose_name='mensagem')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='link')),
                ('is_read', models.BooleanField(default=False, verbose_name='lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lida em')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-created_at'],
            },
        ),
    ]
