# Generated by Django 5.2.17 on 2026-09-15 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TASK_ASSIGNED', 'Tarefa atribuída'), ('TASK_RETURNED', 'Tarefa devolvida'), ('TASK_BLOCKED', 'Tarefa bloqueada'), ('TASK_UNBLOCKED', 'Tarefa desbloqueada'), ('TASK_COMPLETED', 'Tarefa concluída'), ('QUEUE_POSITION_CHANGED', 'Posição na fila alterada'), ('DEADLINE_PROPOSED', 'Novo prazo proposto'), ('DEADLINE_ACCEPTED', 'Prazo aceito'), ('DEADLINE_REJECTED', 'Prazo recusado'), ('DEADLINE_CONFLICT', 'Conflito de prazo'), ('TASK_OVERDUE', 'Tarefa atrasada'), ('ACTIVITY_CREATED', 'Atividade criada'), ('ACTIVITY_COMPLETED', 'Atividade concluída'), ('ACTIVITY_CANCELLED', 'Atividade cancelada'), ('ACTIVITY_REOPENED', 'Atividade reaberta'), ('OWNER_CHANGED', 'Dono alterado')], max_length=24, verbose_name='tipo')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('message', models.CharField(max_length=255, verbose_name='mensagem')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='link')),
                ('is_read', models.BooleanField(default=False, verbose_name='lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lida em')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activities.activity', verbose_name='atividade')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activities.task', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
