# Generated by Django 5.2.17 on 2026-09-16 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Quem delegou, propôs, mencionou ou concluiu — o sujeito da frase da notificação.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='quem gerou o evento'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Tarefa atribuída'), ('TASK_RETURNED', 'Tarefa devolvida'), ('TASK_BLOCKED', 'Tarefa bloqueada'), ('TASK_UNBLOCKED', 'Tarefa desbloqueada'), ('TASK_COMPLETED', 'Tarefa concluída'), ('QUEUE_POSITION_CHANGED', 'Posição na fila alterada'), ('DEADLINE_PROPOSED', 'Novo prazo proposto'), ('DEADLINE_ACCEPTED', 'Prazo aceito'), ('DEADLINE_REJECTED', 'Prazo recusado'), ('DEADLINE_CONFLICT', 'Conflito de prazo'), ('TASK_OVERDUE', 'Tarefa atrasada'), ('ACTIVITY_CREATED', 'Atividade criada'), ('ACTIVITY_COMPLETED', 'Atividade concluída'), ('ACTIVITY_CANCELLED', 'Atividade cancelada'), ('ACTIVITY_REOPENED', 'Atividade reaberta'), ('OWNER_CHANGED', 'Dono alterado'), ('MESSAGE_POSTED', 'Nova mensagem'), ('MENTIONED', 'Você foi mencionado')], max_length=24, verbose_name='tipo'),
        ),
    ]
