# Generated by hand for Django 5.2.17 (sandbox sem runtime Django).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Tarefa atribuída'), ('TASK_ASSIGNMENT_PENDING', 'Atribuição aguardando seu aceite'), ('TASK_ASSIGNMENT_REJECTED', 'Atribuição recusada'), ('TASK_RETURNED', 'Tarefa devolvida'), ('TASK_BLOCKED', 'Tarefa bloqueada'), ('TASK_UNBLOCKED', 'Tarefa desbloqueada'), ('TASK_COMPLETED', 'Tarefa concluída'), ('QUEUE_POSITION_CHANGED', 'Posição na fila alterada'), ('DEADLINE_PROPOSED', 'Novo prazo proposto'), ('DEADLINE_ACCEPTED', 'Prazo aceito'), ('DEADLINE_REJECTED', 'Prazo recusado'), ('DEADLINE_CONFLICT', 'Conflito de prazo'), ('TASK_OVERDUE', 'Tarefa atrasada'), ('ACTIVITY_CREATED', 'Atividade criada'), ('ACTIVITY_COMPLETED', 'Atividade concluída'), ('ACTIVITY_CANCELLED', 'Atividade cancelada'), ('ACTIVITY_REOPENED', 'Atividade reaberta'), ('ACTIVITY_PENDING', 'Atividade pendente'), ('ACTIVITY_APPROVAL_NEEDED', 'Pendência aguardando aprovação'), ('ACTIVITY_APPROVED', 'Pendência aprovada'), ('OWNER_CHANGED', 'Dono alterado'), ('MESSAGE_POSTED', 'Nova mensagem'), ('MENTIONED', 'Você foi mencionado')], max_length=24, verbose_name='tipo'),
        ),
    ]
