# Generated by Django 5.2.17 on 2026-10-01 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_atividade_vira_demanda_nos_rotulos'),
        ('notifications', '0006_process_applied_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activities.activity', verbose_name='demanda'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Tarefa atribuída'), ('TASK_RESPONSAVEL_CHANGED', 'Responsável da tarefa alterado'), ('TASK_ASSIGNMENT_PENDING', 'Atribuição aguardando seu aceite'), ('TASK_ASSIGNMENT_REJECTED', 'Atribuição recusada'), ('TASK_RETURNED', 'Tarefa devolvida'), ('TASK_BLOCKED', 'Tarefa bloqueada'), ('TASK_UNBLOCKED', 'Tarefa desbloqueada'), ('TASK_COMPLETED', 'Tarefa concluída'), ('QUEUE_POSITION_CHANGED', 'Posição na fila alterada'), ('DEADLINE_PROPOSED', 'Novo prazo proposto'), ('DEADLINE_ACCEPTED', 'Prazo aceito'), ('DEADLINE_REJECTED', 'Prazo recusado'), ('DEADLINE_CONFLICT', 'Conflito de prazo'), ('TASK_OVERDUE', 'Tarefa atrasada'), ('ACTIVITY_CREATED', 'Demanda criada'), ('ACTIVITY_COMPLETED', 'Demanda concluída'), ('ACTIVITY_CANCELLED', 'Demanda cancelada'), ('ACTIVITY_REOPENED', 'Demanda reaberta'), ('ACTIVITY_PENDING', 'Demanda pendente'), ('ACTIVITY_APPROVAL_NEEDED', 'Pendência aguardando aprovação'), ('ACTIVITY_APPROVED', 'Pendência aprovada'), ('OWNER_CHANGED', 'Dono alterado'), ('PROCESS_APPLIED', 'Processo aplicado'), ('MESSAGE_POSTED', 'Nova mensagem'), ('MENTIONED', 'Você foi mencionado')], max_length=24, verbose_name='tipo'),
        ),
    ]
